### ISSUE TITLE
Version and only seeing Hot Water Temperature

### ISSUE THREAD

**Issue by SSinSD** [explosivo22/rinnaicontrolr-ha#1]
Starting with 2021.6, Home Assistant requires a version number in the manifest.json file.  I manually added a fake version to get this loaded.

I am able to see two entities:
water_heater.rinnai_water_heater
sensor.rinnai_water_temperature

I see the following errors in the log:

```
2021-06-25 15:13:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 343, in async_update_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Rinnai Water Heater
2021-06-25 15:13:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 343, in async_update_ha_state
    raise NoEntitySpecifiedError(
homeassistant.exceptions.NoEntitySpecifiedError: No entity id specified for entity Rinnai Water Temperature
```

```
2021-06-25 15:23:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
TypeError: 'NoneType' object is not callable
```

My model has a recirculation pump that I am able to activate from the control-R app, I loaded the following service call from HA Developer Tools, but the pump does not activate:
```
service: rinnai.start_recirculation
data:
  entity_id: water_heater.rinnai_water_heater
  duration: 15 
```

**Comment by explosivo22** [comment]
Could you please try this in the new 1.0.33 release.  You will probably need to remove the entry from configuration.yaml and set it up through the integrations tab.  I have not had a chance to test setting it up manually, but this is also a rewrite from the ground up basically.

**Comment by SSinSD** [comment]
I updated to the new release and was able to add via the integration UI, thank you!

**Comment by SSinSD** [comment]
Although all seems to be working well, I do see this error in my home assistant log:

This error originated from a custom integration.

```
Logger: homeassistant.helpers.entity
Source: custom_components/rinnai/device.py:106 
Integration: Rinnai Control-R Water Heater (documentation) 
First occurred: 6:04:30 PM (1 occurrences) 
Last logged: 6:04:30 PM

Update for water_heater.water_heater fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 130, in _request
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
    raise exc
  File "/config/custom_components/rinnai/water_heater.py", line 116, in async_update
    await self._device._update_device()
  File "/config/custom_components/rinnai/device.py", line 106, in _update_device
    self._device_information = await self.api_client.device.get_info(
  File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/device.py", line 22, in get_info
    return await self._request("post", "https://s34ox7kri5dsvdr43bfgp6qh6i.appsync-api.us-east-1.amazonaws.com/graphql",data=payload,headers=GET_PAYLOAD_HEADERS)
  File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 118, in _request
    await self.refreshToken()
  File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 178, in refreshToken
    refresh_response: dict = await self._request(
  File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 133, in _request
    raise RequestError(f"There was an error while requesting {url}") from err
rinnaicontrolr.errors.RequestError: There was an error while requesting https://cognito-idp.us-east-1.amazonaws.com
```

**Comment by explosivo22** [comment]
> Although all seems to be working well, I do see this error in my home assistant log:
> 
> ```
> Logger: homeassistant.helpers.entity
> Source: custom_components/rinnai/device.py:106 
> Integration: Rinnai Control-R Water Heater (documentation) 
> First occurred: 6:04:30 PM (1 occurrences) 
> Last logged: 6:04:30 PM
> 
> Update for water_heater.water_heater fails
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 130, in _request
>     resp.raise_for_status()
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
>     raise ClientResponseError(
> aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://cognito-idp.us-east-1.amazonaws.com')
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 350, in async_update_ha_state
>     await self.async_device_update()
>   File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 558, in async_device_update
>     raise exc
>   File "/config/custom_components/rinnai/water_heater.py", line 116, in async_update
>     await self._device._update_device()
>   File "/config/custom_components/rinnai/device.py", line 106, in _update_device
>     self._device_information = await self.api_client.device.get_info(
>   File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/device.py", line 22, in get_info
>     return await self._request("post", "https://s34ox7kri5dsvdr43bfgp6qh6i.appsync-api.us-east-1.amazonaws.com/graphql",data=payload,headers=GET_PAYLOAD_HEADERS)
>   File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 118, in _request
>     await self.refreshToken()
>   File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 178, in refreshToken
>     refresh_response: dict = await self._request(
>   File "/usr/local/lib/python3.8/site-packages/rinnaicontrolr/api.py", line 133, in _request
>     raise RequestError(f"There was an error while requesting {url}") from err
> rinnaicontrolr.errors.RequestError: There was an error while requesting https://cognito-idp.us-east-1.amazonaws.com
> ```

I have released a new update where I have moved the dependencies to a newly created package.  Looks like this was trying to use an old package that has been changing strictly for console.  Could you try this update and see if this error keeps showing up.  I have been running it for several hours and I don't have that log in mine. Just let me know.

**Comment by SSinSD** [comment]
I have updated and do not see the error so far, I’ll let you know again tomorrow

**Comment by SSinSD** [comment]
I was out of town last week, I am back now.  I have been running version 1.0.37 and have no issues/errors in my logs.  All appears to be working well.  Thanks again!

**Comment by explosivo22** [comment]
Glad to hear everything is working out for you.  I will go ahead and close this issue.
