### ISSUE TITLE
Recirculation switch is not available

### ISSUE THREAD

**Issue by waterboyharris** [explosivo22/rinnaicontrolr-ha#14]
I can find no way to toggle re-circulation. I apologize if I'm missing something that is blatantly obvious. For the sake of being thorough, I'm attaching a pic. I've done a fair amount of reading, uninstalling and reinstalling and still haven't seen the toggle. 
![20210731_061337](https://user-images.githubusercontent.com/8017963/127754394-2b3599fa-8bb0-4937-85c4-c2eff30076b8.jpg)

**Comment by explosivo22** [comment]
Actually there is no toggle. There is a service that can be called to start recirculation. You can set this up in an automation or set up a virtual button to handle it. I will try and make this more clear in the documentation.

**Comment by waterboyharris** [comment]
Thank you so much! I am new to Home Assistant and you gave me enough information that I was able to create recirculation buttons! Thank you for making this integration. Do you have plans or know of a project that is working towards local control of the Control-r module? I really hate when companies force cloud communication for on premises control.

**Comment by explosivo22** [comment]
I do not currently know of any way to control the Rinnai products without the cloud. I am doing more digging, but I haven't heard of any projects or found a way as of yet.

**Comment by explosivo22** [comment]
updated documentation to say starting recirculation is via a service
