### ISSUE TITLE
2021.12 warning

### ISSUE THREAD

**Issue by matt1131** [explosivo22/rinnaicontrolr-ha#17]
Got the following warning after upgrading core to 2021.12.4:

Entity water_heater.water_heater (<class 'custom_components.rinnai.water_heater.RinnaiWaterHeater'>) implements device_state_attributes. Please report it to the custom component author.

Apologies if this isn't formatted correctly or you need more information - first time submitting an issue

**Comment by explosivo22** [comment]
Hey @matt1131,
Sorry to hear this. I have just got around to getting my instance updated to 2021.12.4 and I will investigate. 

Thanks for the heads up.

**Comment by matt1131** [comment]
Thanks for checking it out and also developing this!

**Comment by explosivo22** [comment]
Hey @matt1131,
There should be a new release of 1.0.41 that fixes this issue.  I am glad you are enjoying.

**Comment by matt1131** [comment]
Thanks!
