### ISSUE TITLE
Recirculation time

### ISSUE THREAD

**Issue by shiftylilbastrd** [explosivo22/rinnaicontrolr-ha#19]
I currently have this installed and running on my Unraid machine. 
When calling the service it seems the default recirculation time is 1 hour and the max time is 5 hours. Is this due to Rinnai?
Is there any way to just toggle it on and off without a runtime being specified?

**Comment by explosivo22** [comment]
I just followed how Rinnai had it setup on their end when I did my investigations of how everything worked.  From what I was able to tell, you had to always specify a time for recirculation.  I can run some tests and see if there is a way to just turn it on and off without a time frame, but I believe that this was something set by Rinnai and was unchangeable.

**Comment by explosivo22** [comment]
I did a little more digging and there is no way to just toggle recirculation on and off.  Rinnai automatically adds a value back from my investigations. I may be able to modify the allowed durations that can be sent as either way of some more presets or just allowing custom minutes to be entered, but this might take a little time.

**Comment by shiftylilbastrd** [comment]
Thanks for all your work on this

**Comment by TheChit** [comment]
Was this fixed in the latest update? I just tried changing my script without specifying the time and to my surprise it worked! I don't know how long it will stay on with this setting.

**Comment by explosivo22** [comment]
If it was, it was a side affect. It may just use the last time value you had as the number never truly goes away, but just changes when you change it. I will check into it more though.

**Comment by stowers95120** [comment]
When using the service calls, I am only seeing recirculation staying on for 5 mins (no matter what time I specify as a parameter to the call). Is anyone else seeing this behavior?

**Comment by TheChit** [comment]
Yes - this is a bug with the current control-r setting. Even if you use the app it only runs for 5 minutes at a time unless you use their built in scheduler. When I spoke with their support team, they were aware, but that was almost two months ago. This seems to be a very low priority issue for them.

**Comment by stowers95120** [comment]
Thanks for that info.
Do you see anything wrong with using appdaemon to restart the recirculation every 5 mins?

**Comment by TheChit** [comment]
That is what I've been doing since I noticed this. I basically put a check in place that checks if the recirculation is active every 5 minutes. If it is not running, I turn it back on.

**Comment by explosivo22** [comment]
The 5 minute recirculation bug does still exist.  Might be worth opening up another issue for so we can track the progress separately. To try and answer this question better and the issue that this is related to:

> Was this fixed in the latest update? I just tried changing my script without specifying the time and to my surprise it worked! I don't know how long it will stay on with this setting.

I believe you don't have to call the time as of right now because Rinnai is always remembering the value of 5 minutes.  This never gets cleared out so if you just make a call to start recirculation then it will start with the 5 minute value automatically.  This may work in the future if it keeps the last value used so we will see what happens. I plan on still implementing using a default value if nothing specified.
