### ISSUE TITLE
Rinnai water heater won't start recirc

### ISSUE THREAD

**Issue by dradspinner** [explosivo22/rinnaicontrolr-ha#26]
My Rinnai integration was working great until yesterday and now it won't trigger a recirculation.  I can start recirc on my Control-R app and can see the status of recirc and temperatures in HA, but cannot start the recirc.  Any ideas of what may be happening here?

**Comment by explosivo22** [comment]
I believe this to be related to a recent update for 2022.8.  I will be investigating and hopefully have a fix out soon.

**Comment by explosivo22** [comment]
Upon further investigation, it seems that Rinnai has possibly made a change to their API.  I am digging further to figure out what has changed.

**Comment by dradspinner** [comment]
Thank you for the quick and thorough response.  I'm happy to test any mods and happy to contribute, but I am absolutely not a programmer and bit of a noob at home automation (most of what I'm doing is in Node Red with limited functions as I'm so new at JSON).

**Comment by explosivo22** [comment]
Your welcome. I found out that Rinnai decommissioned part of their API that was be utilized for updating values. I will say it is for the better as they added more authentication, but requires some changes. I should have a fix implemented soon.

**Comment by explosivo22** [comment]
Fix is released. Just let me know if you run into issues, but seems stable on mine.

**Comment by jeremyward** [comment]
Wow are you a rockstar @explosivo22  Thanks so much!!!

**Comment by explosivo22** [comment]
You are very welcome.

**Comment by TheChit** [comment]
Since this update, I've noticed that the recirc only runs for 5 minutes at a time. I've written a script that turns it back on every 5 minutes, but I thought I'd point this out.

**Comment by explosivo22** [comment]
I have noticed the same thing,  but I am also getting the same results using the APP as well.  I'm not sure if Rinnai has something broken or not,  but I'll keep an eye on it.
