### ISSUE TITLE
Getting Sensor Values Interrupts Wall Controllers

### ISSUE THREAD

**Issue by tbully** [explosivo22/rinnaicontrolr-ha#30]
Hello - 
Likely a Rinnai issue but perhaps a feature/change could help.

It appears when this plugin fetches new sensor values (5 minute intervals?) it causes a strange behavior on any controllers connected to the unit (the heater itself or remote wall units).   You can note the heater going through some sort of sequence of values before returning to normal use.

This becomes a problem if you're trying to interact with the controller.  (Not to mention a nuisance if the controller is within sight)

A way to reproduce this is to use the Control-R app.  Simply go to System Status - Refresh Results and you'll see the same.  I'm working with my installer to see if Rinnai can fix this.

But I'm wondering if a feature could be made to adjust the frequency at which these calls are made - even turn it off completely.  Obviously this would be at the detriment of having accurate sensor values but still may be helpful in use-cases where you're just controlling recirculation, etc.

Thanks.

**Comment by explosivo22** [comment]
You are correct in that this is something that Rinnai has implemented.  You can also easily reproduce this in their App as well if you go to the 'Status' tab and hit the Refresh Results button.  The water heater has to go through its maintenance cycles to update the information with the control-r unit.

I will set this as a feature request and see if I can't get something to disable the maintenance interval all together or set it to a custom time.

**Comment by tbully** [comment]
Thank you!  A pain that they've done this.  I'm hopeful that Rinnai will be receptive.  They seem open to ideas.
