### ISSUE TITLE
I cannot get the recerculation switch to show up in home kit.

### ISSUE THREAD

**Issue by wrmacj** [explosivo22/rinnaicontrolr-ha#35]
I have installed the rinnaicontrolr-ha intigration some time ago and it was worked very well and integrated nicley into homekit.  I was able to setup automations in Homekit that also worked well to turn on recirculation, 

I just installed HA on a rasbberyPi4 as well as another VM and I have the rinnaicontrolr-ha installed and configured.  I am able to cick of recurculation via services on HA.
I have tried 1.2.0-1.3.2
I have two problem
The Water temp comes over to Homekit but I wused to be able to go into the properties of the acessore and select something like "display as separate tiles"  This would then display the tempurature tile as well as a swich to turn recirculation on.  At this point I can no longer setup homekit automations or use Siri to turn on recirculation.

![image](https://user-images.githubusercontent.com/109797056/202640956-13916c44-d403-4c49-b4bc-9da7d6422ec5.png)
The second is that the tempurature displayed on homekit is in Celcius when it should be F.

Also this same item is in F on the homeassistant dashbourd while other items are displayed correctly in F.
![image](https://user-images.githubusercontent.com/109797056/202641317-de3449b9-4d1e-4b58-9e0c-9c62003d71d8.png)

I do't know what I missed.  Thanks for any help.

"installation_type": "Home Assistant OS",
    "version": "2022.11.3",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.10.7",
    "docker": true,
    "arch": "aarch64",
    "timezone": "America/Toronto",
    "os_name": "Linux",
    "os_version": "5.15.61-v8",
    "supervisor": "2022.10.2",
    "host_os": "Home Assistant OS 9.3",
    "docker_version": "20.10.18",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "hacs": {
      "version": "1.28.3",
      "requirements": [
        "aiogithubapi>=22.2.4"
      ]
    },
    "rinnai": {
      "version": "1.3.2",
      "requirements": [
        "aiorinnai==0.3.0"
      ]

**Comment by wrmacj** [comment]
As far as the “setting” the water temp panel, it is displayed as Celsius in HomeKit picture #1 is from HomeKit.  But as indicated in picture #2, from homeassistant, it appears that the temp is incorrectly displayed at the source in HA. 

As far as the temp panel no longer haveing the functionality to toggle recirculating on., I can only indicate where I see the problem and identify that it was there before in HomeKit and worked great. I do not know where the problem lies.  I have made numerous new VM’s and new raspberryPi instances and reinstalled the Rinnai integration but I canot recreate the ability to turn on recirculating on HomeKit any more??

**Comment by explosivo22** [comment]
Looks like I may have missed the adjustment for inlet and outlet temperatures.

As far as HA goes, you can call recirculation using a service call. You can tie this to a button manually and add it to a dashboard or something, but it doesn't have functionality to split it out in HA as it is already split based on service calls. 

I wasn't aware Rinnai had native support for homekit. I thought you had to set this up with something through homebridge. Are you setup this way?
