### ISSUE TITLE
Which entity id is needed to call service?

### ISSUE THREAD

**Issue by chrismcneil** [explosivo22/rinnaicontrolr-ha#39]
A recent update removed the water heater entity from home assistant so I no longer know which entity to call the service against to trigger recirculation.

I have tried reinstalling the integration but no luck in getting the entity back.

**Comment by explosivo22** [comment]
You should have an entity that begins with water_heater as the type. You don't have a water heater under controls when you click on the device of the integration?

**Comment by chrismcneil** [comment]
I used to but it is no longer there. When setting up an automation the call service to "Rinnai Control-R Water Heater: Start Recirculation" under Entity I get "No matching entities found".

Under the device I only have sensors.

**Comment by explosivo22** [comment]
Very interesting. You said you have removed the integration and added it back in? I wonder if removing it and removing all references to the water heater might help. I have seen where references have caused entities to get stuck. I am not sure why it would of removed in the first place or why it isn't adding back.

**Comment by chrismcneil** [comment]
1. Removed integration from Devices/Integrations
2. Removed integration from HACS
3. Removed any references on dashboards
4. Removed any references in automations
5. Restarted HA
6. Added integration in HACS and restarted
7. Configured integration
<img width="665" alt="image" src="https://user-images.githubusercontent.com/3980643/204640138-8bb215b8-32ea-4b01-9a91-2bcc7a6642be.png">

**Comment by KoleBarnes** [comment]
Having the same problem. 

`Logger: homeassistant.components.water_heater
Source: custom_components/rinnai/water_heater.py:79
Integration: Water Heater (documentation, issues)
First occurred: 1:29:36 PM (4 occurrences)
Last logged: 1:43:37 PM

Error adding entities for domain water_heater with platform rinnai
Error while setting up rinnai platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 605, in _async_add_entity
    capabilities=entity.capability_attributes,
  File "/usr/src/homeassistant/homeassistant/components/water_heater/__init__.py", line 198, in capability_attributes
    self.hass, self.min_temp, self.temperature_unit, self.precision
  File "/config/custom_components/rinnai/water_heater.py", line 79, in temperature_unit
    return UnitOfTemperature.CELCIUS
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: CELCIUS
`

**Comment by explosivo22** [comment]
Thanks @KoleBarnes. I think I might be able to get this fixed from this.

**Comment by explosivo22** [comment]
Go ahead and give the update a try and this should hopefully get everything back to normal.

**Comment by chrismcneil** [comment]
It's back and I can now use it to call the service thanks!
