### ISSUE TITLE
Incorrect Units displayed

### ISSUE THREAD

**Issue by chrismcneil** [explosivo22/rinnaicontrolr-ha#42]
Using version 1.3.4 my unit shows up as the temperature set to 130C instead of 130F.
The outlet temperature looks correct. It would be nice if we could control which unit is used as often room temperature we will use C but water temperatures we will use F.

<img width="392" alt="image" src="https://user-images.githubusercontent.com/3980643/204705388-e8e362e6-de5f-4a38-8564-41bb5be75e70.png">

**Comment by explosivo22** [comment]
Check your HA settings to be sure. You can go to `Settings -> System -> General` and make sure your units are set correctly there. I changed it to pull from the units of HA.

**Comment by chrismcneil** [comment]
It is set to metric. But trust me the hot water heater is not make 130C water 😂

**Comment by explosivo22** [comment]
I am assuming you are wanting Celsius? 

Does the Rinnai app report Celsius as well?

**Comment by chrismcneil** [comment]
The Control-r app shows F as well as the heater. I'd prefer to be able to choose per value which units to use as I live in a strange land that uses a combination of metric and imperial.

**Comment by explosivo22** [comment]
Ok. Let me check into it. I just changed it to follow HA settings as most integrations I use did the same thing, but I am open to changing things back if it works out. I just found it less code to manage this way,  but we can check it out.

**Comment by explosivo22** [comment]
Yeah HA thinks the value coming in is Celsius so it doesn't do the conversion. The water heater integration doesn't follow the sensors integration that allows you to set the native unit of measurement and then does the conversion for us. We will have to manually make it change for the water heater or get them to fix it.

**Comment by UMB8998** [comment]
Hello, I'm having the exact issue, where you able to resolve it?

**Comment by chrismcneil** [comment]
No sadly still the same issue exists.

**Comment by UMB8998** [comment]
I have made a pull request, is little crude, but it worked for me
https://github.com/explosivo22/rinnaicontrolr-ha/pull/87

**Comment by explosivo22** [comment]
I didn't notice that stale bot closed this. I will check the pull request and see what is going on as well. I know I have been trying to work on a big rewrite and go to straight local configuration as well.

**Comment by explosivo22** [comment]
Just to make sure I understand. You want the water heater temperature to be in F and the sensors to be in either F or C based off what HA has configured?  I am getting that from the pull request.

**Comment by UMB8998** [comment]
Yes, basically the water heater is only sending the values on F, so once HA knows that the value is getting is on F it will automatically convert it to C, on the sensor HA doesn't know is getting a temperature that's why we need to convert it from the integration itself

**Comment by explosivo22** [comment]
Ok. Your pull did successfully change the reported temp of the water heater to always pull F. The sensors that were changed are actually just attributes under the water heater entity that are being updated.  They will report F or C correctly based on HA when pulling individual attributes based off your pull request. 

The other sensors are actually under the sensor.py file which if I read correctly are working as intended?  I know they come in as F, but can be converted over to C based off HA or individually on each sensor with automatic conversion taking place. 

 I just want to make sure I have everything the way it is wanted.

**Comment by UMB8998** [comment]
Yes, that's correct, the sensors had the configuration correct, only the water heater itself had the issues converting the temperature, I have applied those changes on the PR in my HA and here are some pictures attached of the units without the need to do any special conversion in HA

**Water Heater**
![imagen](https://github.com/user-attachments/assets/70e9fc44-1281-4270-ba01-0751f7295165)

**Sensors**
![imagen](https://github.com/user-attachments/assets/7ec35cb2-5e10-4d7f-9f2e-8837821f4b37)

**Water Heater Attributes**
![imagen](https://github.com/user-attachments/assets/fc1e9b00-a283-4eb9-90f5-2d46193288a6)

**Comment by explosivo22** [comment]
Looks good. I have this pulled into my development branch and will release it in the next release. I apologize for letting this slip through on me and not fixing it a long time ago.

**Comment by UMB8998** [comment]
Thank you very much
________________________________

**Comment by chrismcneil** [comment]
Thanks guys!
