### ISSUE TITLE
Change temperature setting with automations

### ISSUE THREAD

**Issue by diy-hard** [explosivo22/rinnaicontrolr-ha#44]
Awesome work on this project!

I think this is a feature request as I haven't found a way to do it (I've checked under devices and services in automation actions).  My water heater "forgets" the temperature I have it set to and reverts to 120F (about once a month, possibly due to occasional power outages).
I'd like to set up a scheduled automation that sets the temp to 130F to correct this issue, but I'm guessing there are some people that actively change the temperature for certain situations that could benefit from the feature as well.

Thank you!

**Comment by explosivo22** [comment]
You can actually do this right now. You can use an action of call service and then call the service `water_heater.set_temperature` and choose the entity of your water heater and set the temperature to your desired temp. I recommend typing in the value and not using the slider.

**Comment by diy-hard** [comment]
Confirmed this works!
Thank you!
