### ISSUE TITLE
The exposed service (rinnai.start_recirculation, rinnai.stop_recirculation) randomly disappears from Home Assistant.

### ISSUE THREAD

**Issue by erwinyang** [explosivo22/rinnaicontrolr-ha#59]
Hi,

I found that the "rinnai" service for starting/stopping recirculation exposed by the integration disappears randomly when I debugged why my recirculation automation stopped working.

When it happens, on the Home Assistant Settings page, there's a repair warning on the top saying "[My automation name] uses an unknown service". I can confirm that the "rinnai" service doesn't exist on the Developer Tools -> Services page.

It seems that reloading the integration solves the issue temporarily each time. But again the service disappears after some time.

**Comment by erwinyang** [comment]
version 1.3.9

**Comment by explosivo22** [comment]
Interesting to say the least. I can't say I have gotten that message on mine yet and I run an automation all the time to start recirculation with my switches. Can you give a run down of what your automation does? I will try to replicate this in my environment.

**Comment by erwinyang** [comment]
It's a pretty simple automation something like if button clicked then call service rinnai.start_recirculation.
I also noticed that when the service disappears (and the entity does still exist when it happens), all the sensor values show Unknown on the device page.

**Comment by erwinyang** [comment]
haven't had this issue again in the recent a few weeks, closing this for now
