### ISSUE TITLE
Most sensors are "Unavailable" if I upgrade to any version of HA 23.X.X

### ISSUE THREAD

**Issue by wrmacj** [explosivo22/rinnaicontrolr-ha#60]
Command completed successfully.
[core-ssh ~]$ ha core update --version 2022.12.6
Processing... Done.

- The Add-on works and shows 12 entities with data

Command completed successfully.
[core-ssh ~]$ ha core update --version 2023.1.1
Processing... Done.
- Most sensors are "Unavailable"  But I can still turn Recirculation on via automations.
- resirculation and water heater heating sensors are working 
- When I check the unavailable sensors I see this message. 
**"This entity is no longer being provided by the rinnai integration. If the entity is no longer in use, delete it in settings."** 

Command completed successfully.
[core-ssh ~]$ ha core update --version 2022.12.6
Processing... Done.

- The Add-on works and shows 12 entities with data
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
If I upgrade I have the following log events after a restart of HASS Core.  I have tried all current versions of 23.1.x and none resolve the issue.
###########################
From logs 
2023-01-27 11:32:23.640 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up rinnai platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/rinnai/sensor.py", line 38, in async_setup_entry
RinnaiOutletTemperatureSensor(device, config_entry.options),
File "/config/custom_components/rinnai/sensor.py", line 60, in __init__
self.options = options
AttributeError: can't set attribute 'options'
##########################

If I 
- remove the add-on via the GUI
-  Restart HA core
-  Re-add the Rinnai add-on
- restart HA Core
The following is observered
The addon installs and only two entities are present.  
Recirculation and Water Heater Heating.

If I 
- Downgrade HASS to 22.12.6 the following is observed.
- all 12 entities show up with no further actions required??

Please let me know if there is anything else I can gather
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

**Comment by explosivo22** [comment]
Apologies as I have been out of schedule. I will investigate and hopefully get a fix pushed soon.

**Comment by wrmacj** [comment]
I just tried again after upgrading to the following and it is broken.

Home Assistant 2023.1.7
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230110.0 - latest

***** 
Info from Banner message and the method I used to upgrade.  It does not matter if I upgrade from teh GUI.
*****

Welcome to the Home Assistant command line.

System information
  IPv4 addresses for enp2s1: 192.168.10.11/24
  IPv6 addresses for enp2s1: fe80::bed2:3557:2f8c:ee8f/64

  OS Version:               Home Assistant OS 9.5
  Home Assistant Core:      **_2022.12.6_**

  Home Assistant URL:       http://HA-VMDK1.local:8123
  Observer URL:             http://HA-VMDK1.local:4357
[core-ssh ~]$ **ha core update --version 2023.1.7**        <-  This is the upgrade,today, but any 23.x breaks it 
Processing... Done.

Command completed successfully.
[core-ssh ~]$ ha core update --version 2022.12.6        <-  reintalling 2022.12.6 fixes it.  Whew!!! 👍 
Processing... Done.

Command completed successfully.


![image](https://user-images.githubusercontent.com/109797056/216019329-573334a4-5d62-4f3a-b9a4-f18b13f877cf.png)

**Comment by wrmacj** [comment]
I did install 23.2.0 today and now joy.  I tried the recirculation scripts and they also no longer work.  When I kick off recirc from teh Rinnai app the recirculation sensor worked and I believe the Water Heater Heating sensor also worked.
Let me know if there is info from my system I can provide.

**Comment by explosivo22** [comment]
Can you confirm that you are on 1.3.9? The fix for this specific error you are getting should have been fixed with this release.

**Comment by wrmacj** [comment]
Can you tell me how to tell?  I do not show any updates in the update section.  Allow HASS to poll for updates is turned on and I do not have any skipped.

**Comment by explosivo22** [comment]
The quickest would be to look at the manifest file in the integration folder and see if it says 1.3.9.

**Comment by wrmacj** [comment]
I deleted the Rinnai integration and restarted HAS.
I upgraded to 23.2.0
I reinstalled the Rinnai integration .
I could not find an integrations folder.
I did find a config\custom_components\rinnai\manifest.json and this is the contents.
    "domain": "rinnai",
    "name": "Rinnai Control-R Water Heater",
    "config_flow": true,
    "documentation": "https://github.com/explosivo22/rinnaicontrolr-ha/",
    "codeowners": [ "@explosivo22" ],
    "requirements": [ "aiorinnai==0.3.1" ],
    "version": "1.3.6",
    "iot_class":  "cloud_polling"

Not sure how to force an upgrade?

**Comment by wrmacj** [comment]
Deleted the dir and re-added via HACCs and it installed 1.3.9.  Rebooting. It shows 11 devices sooooo, it looks good.
I will up in a momement.
Thanks for the hint.

**Comment by wrmacj** [comment]
All Good!  Thanks for the assistance.
