### ISSUE TITLE
GPM

### ISSUE THREAD

**Issue by adhutch** [explosivo22/rinnaicontrolr-ha#64]
I think the GPM Water Flow Rate is off 1 decimal place. The Control R shows 12 GPM and the HA Water Flow Rate sensor shows 1.2 GPM

**Comment by explosivo22** [comment]
I have looked into this and according to my manual and the manual for the control-r the flow rate should be the value read by the control-r x0.1g/min.

You can also view [this](https://www.google.com/url?sa=t&source=web&rct=j&url=https://media.rinnai.us/salsify_asset/s-b3bfdb6e-f136-4ba1-9de3-608e2f2c2cb5/100000564%2520V53De%2520Technical%2520Data%2520Sheet.pdf&ved=2ahUKEwjl0K_zjY3_AhWUtYkEHTafBAEQFnoECCEQAQ&usg=AOvVaw2grlgLtR8y-Um_y1lDPOo0) from Rinnai as well. 

I personally feel that the control-r is incorrect as that seems like a lot of flow. The highest Rinnai I can find is 11 GPM.
