### ISSUE TITLE
Entities Unavailable

### ISSUE THREAD

**Issue by Natclanwy** [explosivo22/rinnaicontrolr-ha#70]
Sometime in the last couple of weeks my hot water heater entities became unavailable and no longer being provided by the integration. I have tried removing the integration and reinstalling with no luck. Did Rinnai or Home Assistant make a change that has broken this integration?

**Comment by explosivo22** [comment]
This is very interesting. I am unable to replicate this as well as #69. Are you running 2023.07.3? I wonder if maybe rinnai is changing something on the backend in small increments.

**Comment by Natclanwy** [comment]
I am running 2023.8.3, the issue started before the beta was released and I upgraded from 2023.07.3. I am also running version 1.40 of the Rinnai integration according to the manifest file.

**Comment by Natclanwy** [comment]
Not sure if this helps but just for my piece of mind I was successfully able to collect data using the method documented in #51

**Comment by andrewradin** [comment]
also have this problem.

**Comment by andrewradin** [comment]
Logger: homeassistant.components.water_heater
Source: helpers/entity_platform.py:619
Integration: Water Heater (documentation, issues)
First occurred: 10:12:29 AM (8 occurrences)
Last logged: 8:46:27 PM

Error adding entities for domain water_heater with platform rinnai
Error while setting up rinnai platform for water_heater
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'

**Comment by andrewradin** [comment]
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:619
Integration: Sensor (documentation, issues)
First occurred: 10:12:29 AM (8 occurrences)
Last logged: 8:46:27 PM

Error adding entities for domain sensor with platform rinnai
Error while setting up rinnai platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 510, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 619, in _async_add_entity
    device = dev_reg.async_get(self.hass).async_get_or_create(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: DeviceRegistry.async_get_or_create() got an unexpected keyword argument 'serial'

**Comment by andrewradin** [comment]
confirmed as fixed thank you
