### ISSUE TITLE
Added to HACS but is no longer there after a restart

### ISSUE THREAD

**Issue by jkosharek** [explosivo22/rinnaicontrolr-ha#72]
Got through step 5:
Added https://github.com/explosivo22/rinnaicontrolr-ha as Integration, it adds and shows in HACS, restart HA to let the integration load, but nothing rinnai is found when I go to add the integration and when I check back in HACS, it's not there after the reboot.

A 2 day old Home Assistance, I have other HACS installs that worked. 

HACS v1.33.0 20230406083157
HA v2023.11.2

**Comment by explosivo22** [comment]
Did anything show up in your logs?

**Comment by jkosharek** [comment]
Not sure where exactly which logs to look in?

**Comment by jkosharek** [comment]
@explosivo22 So in ['Adding HACS Custom Repositories Removed after HA Restart (Issue #3344)'](https://github.com/hacs/integration/issues/3344#issuecomment-1812906211)  HACS says 'Unused custom repositories are cleared out on startup.'

Based on the rinnaicontrolr-ha install instructions it says to restart, which removes the repository. How do I refresh what HA sees from HACS. Looks like the instructions need to be updated.

**Comment by explosivo22** [comment]
Yeah looks like they changed something and I will need to update the instructions. If on a pc, you can do F12 to open dev tools and right click the refresh button and do empty cache and hard refresh. I think then you could go add the integration.

**Comment by jkosharek** [comment]
So once custom repo is added in HACE, you select the new repo in HACS and opens the gitbub page and at the bottom right there is a download icon, click that and then restart HA. After that I waa good to go.
