### ISSUE TITLE
Can't add repository to the store

### ISSUE THREAD

**Issue by tteggelit** [explosivo22/rinnaicontrolr-ha#73]
My install is a  HASSOS install which I believe has HACS preinstalled and configured. In any case, following the HACS instructions for configuration don't show HACS as an available integration to add. So I went to Settings -> Add-ons -> Add-on Store (Button lower right) -> 3 dots -> Repositories and entered the GitHub repo URL in the Add field and click Add. It then says that it's not a valid add-on repository:

<img width="607" alt="Screenshot 2023-11-21 at 7 01 58 PM" src="https://github.com/explosivo22/rinnaicontrolr-ha/assets/3209514/9d33db13-3716-4856-9877-8357fe1f830c">

I can't seem to find anywhere else to add an integration repository. What am I doing wrong?

**Comment by explosivo22** [comment]
You would definitely have to add it as a custom repository through HACS. Have you already added HACS through devices and integrations?

**Comment by tteggelit** [comment]
I knew I had to be doing something stupid, and I went back and re-read everything more carefully and saw that HACS is not the Add-on Store in HASSOS. I added it, restarted, downloaded the Rinnai repo, restarted, and now I think things are up and running. Sorry for making a pointless issue.

**Comment by explosivo22** [comment]
No worries at all. I have definitely done things like this before. Glad everything working.
