### ISSUE TITLE
Update rate 

### ISSUE THREAD

**Issue by rsokoloff** [explosivo22/rinnaicontrolr-ha#74]
Thank you for taking the time and effort to create and maintain this integration. Using this integration and node-red enables me to circumvent the (multiple?) shortcomings of Rinnai's  Control-r app. 

Is it just me or does Rinnai's Control-r app have an abysmal update algorithim? The system can be recirculating
 (I can hear the water running through the pipes and the cold water line is warm after the flow stops) but almost never do the flow rate, heating status, and recirculation status all indicate activity. The water flow rate appears to be the most problematic and it's not uncommon for the system to indicate 'Heating: on' with a flow rate of 0. Sometime I see the opposite with the system indicating water flow but insisting that the heater and recirculation pump are both off. Is this update issue a known problem or is it my installation and I need to do more troubleshooting? I enormously appreciate any feedback. BTW I'm using control-r version 2.5.7 and firmware 238.

<img width="495" alt="Screen Shot 2023-12-03 at 10 34 49 AM" src="https://github.com/explosivo22/rinnaicontrolr-ha/assets/37712809/4bb101a6-043f-4781-956a-99354e9aac5c">

**Comment by explosivo22** [comment]
Rinnai's update process for a lot of sensors is very poor. The control-r module has to make a request to do what they call a maintenance cycle which then updates a decent amount of the sensors like flow rate, inlet temp., and outlet temp. to just name a few.  We run a maintenance cycle currently every 5 minutes because this can be very intensive sometimes on the water heater and I didn't want to be responsible for the water heater to stop responding and have to restart, speaking from experience while testing. I have plans to implement a configurable poll interval to allow the end user to change this, but I don't have this done yet.

**Comment by wrmacj** [comment]
My observations in my implementation is that it seems like the GPM is the item that is the most significantly lacking in updates.  Items like recirculation and heating status are pretty good and are updated very promptly as displayed on the Control-R app.  In my example below even fan speeds and currents are updated fairly frequently.  But GPM just does not get updated with all the other settings.  I think that expectations that the GPM will help determine how much hot water is being used is it isn't happening here but if the updates for GPM were at least as frequent as the fan frequency you could get a rough idea of trends.

Just and FYI on my graphs:
I am in a cold area so you can see when the hot water is on for any period of time the inlet temp goes way down except when the system is recirculating.
Our home is on a hot water "One call only mode"  I have a complete hot water loop that feeds all taps, like a spoke layout.  it takes about one minute to put 125F water to any tap, on call.  We just do a "Siri water on"  Recirculation starts and if the water is below 100, siri reports the temp.   
![image](https://github.com/explosivo22/rinnaicontrolr-ha/assets/109797056/61321d98-d049-48e6-b7d0-9c5bbd6f2216)
Having this integration has been a great help!  Thanks @explosivo22
