### ISSUE TITLE
Deprecated Constants Warning in HA 2024 logs

### ISSUE THREAD

**Issue by Ramias1** [explosivo22/rinnaicontrolr-ha#76]
Getting these messages in my log files; does not currently break functionality.

```
DEVICE_CLASS_TEMPERATURE was used from rinnai, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.TEMPERATURE instead, please report it to the author of the 'rinnai' custom integration
ELECTRIC_CURRENT_MILLIAMPERE was used from rinnai, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfElectricCurrent.MILLIAMPERE instead, please report it to the author of the 'rinnai' custom integration
FREQUENCY_HERTZ was used from rinnai, this is a deprecated constant which will be removed in HA Core 2025.1. Use UnitOfFrequency.HERTZ instead, please report it to the author of the 'rinnai' custom integration
```

**Comment by morikplay** [comment]
Hello,
I use this integration, and have made the rather benign changes, directly in `sensor.py` using Visual Studio Code. Reload of component does not indicate any errors. How best shall i go about submitting it to the repository? I'm rather new to HA, and do not yet have a dev environment setup.

**Comment by morikplay** [comment]
Apologies to @wrmacj  and @explosivo22 for the delayed response. I see that changes in [here](https://github.com/explosivo22/rinnaicontrolr-ha/pull/77) are identical to mine. All good.

**Comment by explosivo22** [comment]
@morikplay No worries. Good of you to get in and get your hands dirty and figure it out before I could get to it. I'm glad our stuff matches.
