### ISSUE TITLE
HA Entities not importing

### ISSUE THREAD

**Issue by crschlaf** [explosivo22/rinnaicontrolr-ha#89]
I'm unable to manually add, see, or use the rinnai.[command]_recirculation entities. The integration recognizes and displays the current recirculation status, but it does not seem to be controllable using the integration.

**Comment by explosivo22** [comment]
If the integration let you add and imported entities, then you should be able to use the service under developer tools to call the "start recirculation" service.

**Comment by crschlaf** [comment]
The entities work when a custom button is created.
